### PR TITLE
Make --sign an alias to -s

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by thefloweringash** [comment]
Thanks!

**Comment by isuruf** [comment]
Thanks @thefloweringash for the review. Can you make a new release with this please?

**Comment by thefloweringash** [comment]
Sorry for the delay, I've pushed a tag: [v0.1.3](https://github.com/thefloweringash/sigtool/releases/tag/v0.1.3).

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
